Initializing SODA source and service files (SODA-1.0 status)
ivoa-std/SODA pull request #8
Opened 2020-05-14 17:52 UTC by Bonnarel

2020-08-05 17:16 UTC, pdowler requested changes
ivoatex subdir is not set up as a submodule; it appears to be a local copy
COPYING is GNU GPL - we agreed that all standards are licensed under CC-BY-SA-4.0
The source file should be named SODA.tex

2020-11-18 13:38 UTC, Bonnarel commented
> ivoatex subdir is not set up as a submodule; it appears to be a local copy
> COPYING is GNU GPL - we agreed that all standards are licensed under CC-BY-SA-4.0
> The source file should be named SODA.tex

Hi Pat, Should be solved eventually. Can you vaildate it now ? Thanks

2021-01-05 18:09 UTC, pdowler requested changes
The .gitmodules looks correct ... will see if it is working correctly once merged and pulled by others. Also, I added the CI buld to master so when you make the change below it should try to build.

One change: ivoatextmeta.tex should not be included - it gets generated each time

2021-01-20 18:29 UTC, pdowler approved these changes

2021-01-20 18:29 UTC, merged